CREATE TABLE REGISTER_INTERFACE
   (	
   	ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  
  APP_NAME VARCHAR(20) NOT NULL, 
  TINKER_VERSION VARCHAR(20) NOT NULL, 
  INTERFACE_NAME VARCHAR(500) NOT NULL, 
  INTERFACE_VERSION VARCHAR(20), 
  PROVIDER_ADDRESS VARCHAR(20) NOT NULL, 
  PUBLISH_TIME datetime NOT NULL,
  STATUS VARCHAR(20) NOT NULL,  
  TIMEOUT int NOT NULL, 
  SERIALIZABLE_TYPE VARCHAR(10) NOT NULL,
  primary key(id)
); 
    
CREATE TABLE REGISTER_INTERFACE_METHOD
   (  
    ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL, 
  INTERFACE_ID int NOT NULL, 
  METHOD_NAME VARCHAR(500) NOT NULL, 
  PARAM_TYPE VARCHAR(1000) NOT NULL, 
  RESPONSE_TYPE VARCHAR(500) NOT NULL,
  primary key(id)
   );
  