CREATE TABLE CONFIG(
    ID INT NOT NULL auto_increment,
    GMT_CREATE datetime NOT NULL,
    GMT_MODIFIED datetime NOT NULL,
    APP_NAME VARCHAR(20) NOT NULL,
    DATA_GROUP VARCHAR(20) NOT NULL,
    DATA_ID VARCHAR(200) NOT NULL,
    DATA_VALUE VARCHAR(2000) NOT NULL,
    CLIENT_IP VARCHAR(20) NOT NULL,
    STATUS INT NOT NULL,
    MIDDLEWARE VARCHAR(10) NOT NULL,
    ATTRIBUTES VARCHAR(2000) NOT NULL,
    primary key(id)
);
