CREATE TABLE REGISTER_INTERFACE
   (	
   	ID NUMBER(12,0) NOT NULL ENABLE, 
  GMT_CREATE DATE NOT NULL ENABLE, 
  CREATOR VARCHAR2(128 BYTE) NOT NULL ENABLE, 
  GMT_MODIFIED DATE NOT NULL ENABLE, 
  MODIFIER VARCHAR2(128 BYTE) NOT NULL ENABLE, 
  IS_DELETED CHAR(1 BYTE) NOT NULL ENABLE,  
  APP_NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
  TINKER_VERSION VARCHAR2(20 BYTE) NOT NULL ENABLE, 
  INTERFACE_NAME VARCHAR2(500 BYTE) NOT NULL ENABLE, 
  INTERFACE_VERSION VARCHAR2(20 BYTE), 
  PROVIDER_ADDRESS VARCHAR2(20 BYTE) NOT NULL ENABLE, 
  PUBLISH_TIME DATE NOT NULL ENABLE,
  STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE,  
  TIMEOUT NUMBER(12,0) NOT NULL ENABLE, 
  SERIALIZABLE_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE  
   );
   
create sequence SEQ_REGISTER_INTERFACE
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

CREATE TABLE REGISTER_INTERFACE_METHOD
   (  
     ID NUMBER(12,0) NOT NULL ENABLE, 
  GMT_CREATE DATE NOT NULL ENABLE, 
  CREATOR VARCHAR2(128 BYTE) NOT NULL ENABLE, 
  GMT_MODIFIED DATE NOT NULL ENABLE, 
  MODIFIER VARCHAR2(128 BYTE) NOT NULL ENABLE, 
  IS_DELETED CHAR(1 BYTE) NOT NULL ENABLE,  

  INTERFACE_ID NUMBER(12,0) NOT NULL ENABLE, 
  METHOD_NAME VARCHAR2(500 BYTE) NOT NULL ENABLE, 
  PARAM_TYPE VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
  RESPONSE_TYPE VARCHAR2(500 BYTE) NOT NULL ENABLE
   );
   
create sequence SEQ_REGISTER_CENTER_METHOD
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;